[package]
name = "carbon_locker"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.6.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }
carbon_v3 = { git = "https://github.com/carbonable-labs/carbon-protocol-v3.git" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.26.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
